GET http://localhost:5000/api/user/e1JhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2I3ZGY4ZTllZDQxNDYwOGM1NDk1ZDQiLCJlbWFpbCI6InBvdHRlckBob2d3YXJ0cy5jb20iLCJpYXQiOjE2NzMzMzU2NzgsImV4cCI6MTY3MzMzOTI3OH0.hrj_f0f_ehbw1HsrzZD9ngeYSYKfJvaGyY33o6B1AJs HTTP/1.1