POST http://localhost:5000/api/user/sign-up HTTP/1.1
Content-Type: application/json

{
    "firstName": "Herminy",
    "lastName": "Wesley",
    "birthday": "1990-02-02",
    "email": "ron@hogwarts.com",
    "password": "leviosa"
}