DELETE http://localhost:5000/api/tasks/63bef0ee14dd660601be3553 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2I3ZGY4ZTllZDQxNDYwOGM1NDk1ZDQiLCJlbWFpbCI6InBvdHRlckBob2d3YXJ0cy5jb20iLCJpYXQiOjE2NzM1OTc4NTUsImV4cCI6MTY3MzU5NzkxNX0.b84BDHm2b9fGnOnt_RdRqRyfPrfGij-ALVj95C0uGL0