POST http://localhost:5000/api/users/refresh HTTP/1.1
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2I3ZGY4ZTllZDQxNDYwOGM1NDk1ZDQiLCJlbWFpbCI6InBvdHRlckBob2d3YXJ0cy5jb20iLCJpYXQiOjE2NzQxMjAwMDYsImV4cCI6MTY3NDEyMzYwNn0.xMVF6JODBQkaoGyW9fkMds0bmOQMvIWNlj6SuVQZYXI"
}